apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-html
  namespace: myapp2
data:
  index.html: |
    This is my personalised index.html
  configmap.html: |
    This is my ConfigMap page !
