apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.mygroup.myapi.com
spec:
  group: mygroup.myapi.com
  names:
    kind: MyCRD
    singular: mycrd
    plural: mycrds
    shortnames:
      - mcrd
  # Namespaced or Cluster
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          # True or undefined
          x-kubernetes-preserve-unknown-fields: true
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
              type: object
              properties:
                magicnumber:
                  type: integer
                  minimum: 1
                  maximum: 42

