apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-app-local-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: my-app-storageclass
  hostPath:
    path: /tmp/my-local-pv
