apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-app-alert
  namespace: myapp
spec:
  groups:
  - name: my-app
    rules:
    - alert: MyAppTooManyReplicas
      expr: count by(service) (health_count_total{namespace="myapp"}) >= 2
