apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-local-storageclass
  namespace: myapp
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
