apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-service-reader-role
  namespace: nginx
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
