apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-secret-reader-role
  namespace: nginx
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
