apiVersion: v1
kind: DeploymentConfig
metadata:
  name: nginx-deployment-config
spec:
  selector:
    app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

