apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: image-registry.openshift-image-registry.svc:5000/default/nginx:1.25.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 3
              memory: "100Mi"
            limits:
              cpu: 3
              memory: "200Mi"
      serviceAccountName: nginx-sa

