apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-scc-user-rolebinding
  namespace: nginx
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    apiGroup: ""
roleRef:
  kind: Role
  name: my-scc-user-role
  apiGroup: rbac.authorization.k8s.io
