kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "my-nginx-buildconfig"
  namespace: docker-builds
spec:
  runPolicy: "Serial"
  triggers:
    - type: "ImageChange"
    - type: "ConfigChange"
  source:
    dockerfile: |
      FROM nginx:1.19.6
      ENV MYVAR "MyVariableContent"
      RUN cp /usr/share/nginx/html/index.html /usr/share/nginx/html/myindex.html
  strategy:
    dockerStrategy:
      #noCache: true
      from:
        kind: "DockerImage"
        name: "nginx:1.19.6"
      # Bypass rate limit
      #pullSecret:
      #  name: "training"
  output:
    to:
      kind: "ImageStreamTag"
      name: "my-nginx:latest"
