apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-local-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: crc-csi-hostpath-provisioner
  #storageClassName: ""
  resources:
    requests:
      storage: 10Mi
