apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-toolbox-sa-cluster-admin-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: my-toolbox-sa
    namespace: mytoolbox
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
