apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: my-toolbox
  namespace: mytoolbox
  annotations:
    openshift.io/display-name: my-toolbox-is
spec:
  lookupPolicy:
    local: true
