apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-toolbox-pvc
  namespace: mytoolbox
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  #storageClassName: my-local-storageclass
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
