apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-reader-rolebinding
  namespace: mytoolbox
subjects:
  - kind: ServiceAccount
    name: test
    apiGroup: ""
roleRef:
  kind: Role
  name: my-service-reader-role
  apiGroup: rbac.authorization.k8s.io
