apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-admin-user-rolebinding
  namespace: nginx
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    namespace: nginx
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
