apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-scc-user-rolebinding
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    apiGroup: ""
  # Needed in more recent OC versions as pre/post hook are apparently not played with the defined user, but with default
  - kind: ServiceAccount
    name: default
    apiGroup: ""
  # Needed in more recent OC versions as pre/post hook are apparently not played with the defined user, but with deployer
  - kind: ServiceAccount
    name: deployer
    apiGroup: ""
roleRef:
  kind: Role
  name: my-scc-user-role
  apiGroup: rbac.authorization.k8s.io
