apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: monitor-demo-hpa
  namespace: monitor-demo-app
spec:
  scaleTargetRef:
    kind: Deployment
    name: monitor-demo-app
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 1
