apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alert
spec:
  groups:
  - name: example
    rules:
    - alert: HighTrafficAlert
      expr: rate(application_org_example_rbaumgar_GreetingResource_greetings_total[2m]) > 1
